.TH lowbatt 1 "Feb 17, 2022"

.SH NAME
lowbatt \- Low Battery Notifications

.SH SYNOPSIS
.sp
\fBlowbatt\fP [\fIoptions\fP] \fI<command>\fP

.SH DESCRIPTION
.sp
\fBlowbatt\fP is a program for automatically notifying of battery status at set thresholds to optimize battery lifetime or to know when to plug in.

.SH OPTIONS
.TP
\fB  \-\-help\fP
Show help message and exit

.SH COMMANDS
.TP
\fB  get\fP
Display current configuration

.TP
\fB  set\fP
Set a value in configuration

.TP
\fB  invoke\fP
Internal command for service to call

.SH EXAMPLES
.sp
Check current configuration
.RS 4
\fBlowbatt get\fP
.RE

.sp
Set configuration
.nf
.RS 4
\fBlowbatt set low_threshold 20\fP
.RE

.SH LICENSE
.sp
Apache License 2.0, see LICENSE.

.SH AUTHOR
Brian Meneley
